// assets
AIRDROP_MULT_STREAK_NAME   = "airdrop_multiple";
AIRDROP_MULT_VEHICLE_MODEL = "veh8_mil_air_acharlie130_ks";

// ac130
AIRDROP_MULT_AC130_MAX_HEALTH = 1000;
AIRDROP_MULT_AC130_POINTS     = 400;

// drop
AIRDROP_MULT_NUM_CRATES = 3;

AIRDROP_MULT_AC130_HEIGHT_OFFSET              = 200;
AIRDROP_MULT_AC130_HEIGHT_OFFSET_PER_INSTANCE = 300;

// anim
AIRDROP_MULT_AC130_ANIM_BASE_NAME = "ac130";

AIRDROP_MULT_CRATE_ANIM_BASE_NAME = "care_package";

AIRDROP_MULT_CRATE_1_ANIM_BASE_NAME = AIRDROP_MULT_CRATE_ANIM_BASE_NAME + "_1";
AIRDROP_MULT_CRATE_2_ANIM_BASE_NAME = AIRDROP_MULT_CRATE_ANIM_BASE_NAME + "_2";
AIRDROP_MULT_CRATE_3_ANIM_BASE_NAME = AIRDROP_MULT_CRATE_ANIM_BASE_NAME + "_3";

AIRDROP_MULT_CHUTE_ANIM_BASE_NAME = "care_package_chute";

AIRDROP_MULT_CHUTE_1_ANIM_BASE_NAME = AIRDROP_MULT_CHUTE_ANIM_BASE_NAME + "_1";
AIRDROP_MULT_CHUTE_2_ANIM_BASE_NAME = AIRDROP_MULT_CHUTE_ANIM_BASE_NAME + "_2";
AIRDROP_MULT_CHUTE_3_ANIM_BASE_NAME = AIRDROP_MULT_CHUTE_ANIM_BASE_NAME + "_3";

AIRDROP_MULT_ANIM_NAME = "care_package_drop_multiple";

AIRDROP_MULT_CRATE_1_OFFSET = ( 0, 0, 0 );
AIRDROP_MULT_CRATE_2_OFFSET = ( 250, 0, 0 );
AIRDROP_MULT_CRATE_3_OFFSET = ( -250, 0, 0 );

// ui
AIRDROP_MULT_MINIMAP_ICON = "icon_minimap_dropship";

// fx
AIRDROP_MULT_AC130_RUNNING_SOUND = "iw8_bradley_drop_c130";
AIRDROP_MULT_AC130_DEATH_CALLOUT = "callout_destroyed_ac130";