// vehicle
APC_RUS_VEHICLE_REF    = "apc_russian";
APC_RUS_VEHICLE_TYPE   = "vindia_physics_mp";
APC_RUS_VEHICLE_MODEL  = "veh8_mil_lnd_vindia_a1_physics_mp";
APC_RUS_VEHICLE_WEAPON = "apc_rus_mp";

// seats
APC_RUS_DRIVER_SEAT_REF   = "driver";
APC_RUS_F_REAR_SEAT_REF   = "front_rear";
APC_RUS_MFL_REAR_SEAT_REF = "middle_front_left_rear";
APC_RUS_MFR_REAR_SEAT_REF = "middle_front_right_rear";
APC_RUS_MBL_REAR_SEAT_REF = "middle_back_left_rear";
APC_RUS_B_REAR_SEAT_REF   = "back_rear";

APC_RUS_DRIVER_SEAT_TAG   = "tag_seat_0";
APC_RUS_F_REAR_SEAT_TAG   = "tag_seat_1";
APC_RUS_MFL_REAR_SEAT_TAG = "tag_seat_2";
APC_RUS_MBL_REAR_SEAT_TAG = "tag_seat_3";
APC_RUS_MFR_REAR_SEAT_TAG = "tag_seat_4";
APC_RUS_B_REAR_SEAT_TAG   = "tag_seat_5";

APC_RUS_ENTER_HINT_MAX_MOVE_SPEED_SQR = 100 * 100;

// exiting
APC_RUS_EXIT_EXTENTS_FRONT  = 136;
APC_RUS_EXIT_EXTENTS_BACK   = 129;
APC_RUS_EXIT_EXTENTS_LEFT   = 68;
APC_RUS_EXIT_EXTENTS_RIGHT  = 68;
APC_RUS_EXIT_EXTENTS_TOP    = 87;
APC_RUS_EXIT_EXTENTS_BOTTOM = 0;

APC_RUS_EXIT_CAST_UP_OFFSET          = 65;
APC_RUS_EXIT_CAST_UP_OFFSET_INVERTED = 22;
APC_RUS_EXIT_CAST_DOWN_DISTANCE      = 80;

APC_RUS_ROOF_HEIGHT = 112;

// damage
APC_RUS_MAX_HEALTH = 2700;
APC_RUS_MAX_HITS   = 13;

APC_RUS_EXPLODE_MAX_DAMAGE = 140;
APC_RUS_EXPLODE_MIN_DAMAGE = 70;
APC_RUS_EXPLODE_RADIUS     = 256;

// mines
APC_RUS_MINE_EXTENTS_FRONT      = 115;
APC_RUS_MINE_EXTENTS_BACK       = 110;
APC_RUS_MINE_EXTENTS_LEFT       = 61;
APC_RUS_MINE_EXTENTS_RIGHT      = 61;
APC_RUS_MINE_EXTENTS_BOTTOM     = 25;
APC_RUS_MINE_DISTANCE_TO_BOTTOM = APC_RUS_MINE_EXTENTS_BOTTOM + 15;
APC_RUS_MINE_LOS_CHECK_OFFSET   = ( 0, 0, 50 );

// fx
APC_RUS_EXPLODE_TAG = "tag_origin";
APC_RUS_EXPLODE_FX  = "vfx/iw8/veh/scriptables/vfx_veh_explosion_sedan.vfx";
APC_RUS_EXPLODE_SFX = "car_explode";

APC_RUS_EXPLODE_EQ_SCALE    = 0.4;
APC_RUS_EXPLODE_EQ_RADIUS   = 0.7;
APC_RUS_EXPLODE_EQ_DURATION = 800;

APC_RUS_EXPLODE_PHYS_SCALE        = 1;
APC_RUS_EXPLODE_PHYS_OUTER_RADIUS = 500;
APC_RUS_EXPLODE_PHYS_INNER_RADIUS = 200;

APC_RUS_DUST_MIN_SPEED = 400;

// mp only
APC_RUS_SPAWN_MAX_INSTANCE_COUNT = 30;
APC_RUS_SPAWN_PRIORITY           = 50;

// damage modification - explosive damage
APC_RUS_C4_HITS_PER_ATTACK      = 7;
APC_RUS_AT_MINE_HITS_PER_ATTACK = 7;

// % based damage modification (bullet damage)
APC_RUS_MG_DAMAGE_MODIFIER     = - 0.25;
APC_RUS_RIFLE_DAMAGE_MODIFIER  = - 0.5;
APC_RUS_SMG_DAMAGE_MODIFIER    = -1;
APC_RUS_PISTOL_DAMAGE_MODIFIER = -1;
APC_RUS_SPREAD_DAMAGE_MODIFIER = -1;
APC_RUS_SNIPER_DAMAGE_MODIFIER = 1;

// quake ed
APC_RUS_SPAWN_FLAG_DONT_SPAWN_BIT = 1;
