
EXECUTION_TABLE = "mp_cp/executiontable.csv";

EXECUTION_TABLE_COL_ID          = 0;
EXECUTION_TABLE_COL_REF         = 1;
EXECUTION_TABLE_COL_EXECUTION   = 2;
EXECUTION_TABLE_COL_PROP_WEAPON = 3;

EXECUTION_DEFAULT_REF = "neck_stab";