THROW_KNIFE_EQUIP_REF   = "equip_throwing_knife";
THROW_KNIFE_WEAPON_NAME = "throwingknife_mp";

THROW_KNIFE_MAX_PICKUPS = 12;

THROW_KNIFE_PICKUP_RADIUS = 64;
THROW_KNIFE_PICKUP_HEIGHT = 64;

THROW_KNIFE_PICKUP_TIMEOUT = 20;