VEH_MINE_TRIGGER_UPDATE_INTERVAL = 0.05;

VEH_MINE_TRIGGER_FRONT_EXTENTS    = 90;
VEH_MINE_TRIGGER_BACK_EXTENTS     = 115;
VEH_MINE_TRIGGER_LEFT_EXTENTS     = 38;
VEH_MINE_TRIGGER_RIGHT_EXTENTS    = 38;
VEH_MINE_TRIGGER_BOTTOM_EXTENTS   = 20;
VEH_MINE_TRIGGER_DIST_TO_BOTTOM   = VEH_MINE_TRIGGER_BOTTOM_EXTENTS + 15;
VEH_MINE_TRIGGER_LOS_CHECK_OFFSET = ( 0, 0, 37 );

VEHICLE_MINE_TRIGGER_RADIUS = 10;

VEHICLE_MINE_TRIGGER_IGNORE_2D_RADIUS_SQR = 600 * 600;

VEHICLE_MINE_TRIGGER_MIN_VELOCITY_SQR         = 10 * 10;
VEHICLE_MINE_TRIGGER_MIN_ANGULAR_VELOCITY_SQR = 20 * 20;
