WEAPON_VARIANTS_REF_PREFIX = "mp/gunsmith/";

WEAPON_VARIANTS_COL_VAR_ID             = 0;
WEAPON_VARIANTS_COL_UNIQUE_REF         = 1;
WEAPON_VARIANTS_COL_ROOT               = 2;
WEAPON_VARIANTS_COL_ASSET              = 3;
WEAPON_VARIANTS_COL_DEFAULTS           = 4;
WEAPON_VARIANTS_COL_ATTACH_MUZZLE      = 5;
WEAPON_VARIANTS_COL_ATTACH_BARREL      = 6;
WEAPON_VARIANTS_COL_ATTACH_SIDE        = 7;
WEAPON_VARIANTS_COL_ATTACH_UNDERBARREL = 8;
WEAPON_VARIANTS_COL_ATTACH_OPTIC       = 9;
WEAPON_VARIANTS_COL_ATTACH_MAG         = 10;
WEAPON_VARIANTS_COL_ATTACH_REARGRIP    = 11;
WEAPON_VARIANTS_COL_ATTACH_STOCK       = 12;
WEAPON_VARIANTS_COL_ATTACH_PERK        = 13;
WEAPON_VARIANTS_COL_ATTACH_TRIGGER     = 14;
WEAPON_VARIANTS_COL_ATTACH_OTHER       = 15;
WEAPON_VARIANTS_COL_ATTACH_EXTRA       = 16;


